---
- name: config-firewall | Install iptables
  ansible.builtin.apt:
    name: iptables

- name: config-firewall | Disable IPV6
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
  loop: "{{ data | dict2items }}"
  vars:
    data:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.lo.disable_ipv6: 1

- name: config-firewall | Incomming allow ssh
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 22
    jump: ACCEPT

- name: config-firewall | Incoming drop policy
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: config-firewall | Incomming accept establish/related
  ansible.builtin.iptables:
    chain: INPUT
    match: conntrack
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: ACCEPT
