---
- name: System Update
  ansible.builtin.import_tasks: system-update.yml

- name: NTP configuration
  ansible.builtin.import_tasks: config-ntp.yml

- name: TimeZone Configuration
  ansible.builtin.import_tasks: config-timezone.yml

- name: Firewall Configuration
  ansible.builtin.import_tasks: config-firewall.yml

- name: SSHD Configuration
  ansible.builtin.import_tasks: config-sshd.yml

- name: Automation Account
  ansible.builtin.import_tasks: user-automation.yml

- name: Root Account
  ansible.builtin.import_tasks: user-root.yml
